DELETE FROM PAY_MULTIPLIERS;
DELETE FROM USC;
DELETE FROM PAYE;
DELETE FROM PRSI;
DELETE FROM RATE;
DELETE FROM SIPTU;
DELETE FROM TAXATION;
DELETE FROM STAFF_PAID;
DELETE FROM CONTACT;
DELETE FROM BANKING;
DELETE FROM STAFF;

INSERT INTO PAY_MULTIPLIERS
VALUES(1.50, 2.00, 1.00, 0.60);

INSERT INTO STAFF
VALUES(001,'David', 'O Sullivan', DATE '1990-01-03','m','n',0,'y','a');

INSERT INTO STAFF
VALUES(002,'Maire', 'Deane',      DATE '1987-07-04','f','n',0,'y','b');

INSERT INTO RATE
VALUES('a', 9.55);

INSERT INTO TAXATION
VALUES(001,'a','a','a','a','a');

COMMIT;